// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // ── Web ───────────────────────────────────────────────────────────────────
  // TODO: Replace the values below with your actual Firebase Web app config.
  // Go to: Firebase Console → Project Settings → Your Apps → Add app → Web

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD57VughjWhhfyIseQzoZkVdBuXpC68nbE',
    appId: '1:488423086096:web:048370dde5b7b705049295',
    messagingSenderId: '488423086096',
    projectId: 'findfy-new',
    authDomain: 'findfy-new.firebaseapp.com',
    storageBucket: 'findfy-new.firebasestorage.app',
    measurementId: 'G-S87LGRPJ8W',
  );

  // Then copy the firebaseConfig values here.

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrGKuA77Mvx0PNktEZPWTSNUN9pES-Iis',
    appId: '1:488423086096:android:cced938c5083df64049295',
    messagingSenderId: '488423086096',
    projectId: 'findfy-new',
    storageBucket: 'findfy-new.firebasestorage.app',
  );

  // ── Android ───────────────────────────────────────────────────────────────

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD57VughjWhhfyIseQzoZkVdBuXpC68nbE',
    appId: '1:488423086096:web:caeb90f33021109d049295',
    messagingSenderId: '488423086096',
    projectId: 'findfy-new',
    authDomain: 'findfy-new.firebaseapp.com',
    storageBucket: 'findfy-new.firebasestorage.app',
    measurementId: 'G-N3YVWMPWEQ',
  );

}